#!/bin/bash

set -x

# Close stdin
exec 0>&-

# List stuff
uname -a
ls -l /dev/loop*
sudo losetup -a
sudo losetup -f
sudo lsmod

# Make everything fail
exit 1

# Remove remnants of apparmor (specific to Travis VM)
sudo dpkg --purge apparmor

# Install dependencies
sudo apt-get -y install debootstrap quota

cd warden
bundle install
rvmsudo bundle exec rake setup[config/linux.yml]
rvmsudo bundle exec rake spec
