barrier.o: barrier.c barrier.h util.h
mount.o: mount.c mount.h
msg.o: msg.c msg.h
pump.o: pump.c pump.h util.h
un.o: un.c un.h util.h
util.o: util.c util.h
wsh.o: wsh.c msg.h pump.h un.h
wshd.o: wshd.c barrier.h msg.h mount.h un.h util.h
