source "http://rubygems.org"

gem "rake"
gem "steno", "~> 0.0.15"
gem "membrane"
gem "eventmachine", "~> 1.0.0"
gem "em-posix-spawn"
gem "sys-filesystem"
gem "yajl-ruby"

gem "warden-protocol"
gem "warden-client"

group :spec do
  gem "rspec"
end
