// Code generated by protoc-gen-go.
// source: bundle
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CreateRequest_BindMount_Mode int32

const (
	CreateRequest_BindMount_RO CreateRequest_BindMount_Mode = 0
	CreateRequest_BindMount_RW CreateRequest_BindMount_Mode = 1
)

var CreateRequest_BindMount_Mode_name = map[int32]string{
	0: "RO",
	1: "RW",
}
var CreateRequest_BindMount_Mode_value = map[string]int32{
	"RO": 0,
	"RW": 1,
}

func (x CreateRequest_BindMount_Mode) Enum() *CreateRequest_BindMount_Mode {
	p := new(CreateRequest_BindMount_Mode)
	*p = x
	return p
}
func (x CreateRequest_BindMount_Mode) String() string {
	return proto.EnumName(CreateRequest_BindMount_Mode_name, int32(x))
}
func (x CreateRequest_BindMount_Mode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *CreateRequest_BindMount_Mode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CreateRequest_BindMount_Mode_value, data, "CreateRequest_BindMount_Mode")
	if err != nil {
		return err
	}
	*x = CreateRequest_BindMount_Mode(value)
	return nil
}

type Message_Type int32

const (
	Message_Error          Message_Type = 1
	Message_Create         Message_Type = 11
	Message_Stop           Message_Type = 12
	Message_Destroy        Message_Type = 13
	Message_Info           Message_Type = 14
	Message_Spawn          Message_Type = 21
	Message_Link           Message_Type = 22
	Message_Run            Message_Type = 23
	Message_Stream         Message_Type = 24
	Message_NetIn          Message_Type = 31
	Message_NetOut         Message_Type = 32
	Message_CopyIn         Message_Type = 41
	Message_CopyOut        Message_Type = 42
	Message_LimitMemory    Message_Type = 51
	Message_LimitDisk      Message_Type = 52
	Message_LimitBandwidth Message_Type = 53
	Message_Ping           Message_Type = 91
	Message_List           Message_Type = 92
	Message_Echo           Message_Type = 93
)

var Message_Type_name = map[int32]string{
	1:  "Error",
	11: "Create",
	12: "Stop",
	13: "Destroy",
	14: "Info",
	21: "Spawn",
	22: "Link",
	23: "Run",
	24: "Stream",
	31: "NetIn",
	32: "NetOut",
	41: "CopyIn",
	42: "CopyOut",
	51: "LimitMemory",
	52: "LimitDisk",
	53: "LimitBandwidth",
	91: "Ping",
	92: "List",
	93: "Echo",
}
var Message_Type_value = map[string]int32{
	"Error":          1,
	"Create":         11,
	"Stop":           12,
	"Destroy":        13,
	"Info":           14,
	"Spawn":          21,
	"Link":           22,
	"Run":            23,
	"Stream":         24,
	"NetIn":          31,
	"NetOut":         32,
	"CopyIn":         41,
	"CopyOut":        42,
	"LimitMemory":    51,
	"LimitDisk":      52,
	"LimitBandwidth": 53,
	"Ping":           91,
	"List":           92,
	"Echo":           93,
}

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}
func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (x Message_Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Message_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Type_value, data, "Message_Type")
	if err != nil {
		return err
	}
	*x = Message_Type(value)
	return nil
}

type CopyInRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	SrcPath          *string `protobuf:"bytes,2,req,name=src_path" json:"src_path,omitempty"`
	DstPath          *string `protobuf:"bytes,3,req,name=dst_path" json:"dst_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CopyInRequest) Reset()         { *this = CopyInRequest{} }
func (this *CopyInRequest) String() string { return proto.CompactTextString(this) }
func (*CopyInRequest) ProtoMessage()       {}

func (this *CopyInRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *CopyInRequest) GetSrcPath() string {
	if this != nil && this.SrcPath != nil {
		return *this.SrcPath
	}
	return ""
}

func (this *CopyInRequest) GetDstPath() string {
	if this != nil && this.DstPath != nil {
		return *this.DstPath
	}
	return ""
}

type CopyInResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *CopyInResponse) Reset()         { *this = CopyInResponse{} }
func (this *CopyInResponse) String() string { return proto.CompactTextString(this) }
func (*CopyInResponse) ProtoMessage()       {}

type CopyOutRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	SrcPath          *string `protobuf:"bytes,2,req,name=src_path" json:"src_path,omitempty"`
	DstPath          *string `protobuf:"bytes,3,req,name=dst_path" json:"dst_path,omitempty"`
	Owner            *string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CopyOutRequest) Reset()         { *this = CopyOutRequest{} }
func (this *CopyOutRequest) String() string { return proto.CompactTextString(this) }
func (*CopyOutRequest) ProtoMessage()       {}

func (this *CopyOutRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *CopyOutRequest) GetSrcPath() string {
	if this != nil && this.SrcPath != nil {
		return *this.SrcPath
	}
	return ""
}

func (this *CopyOutRequest) GetDstPath() string {
	if this != nil && this.DstPath != nil {
		return *this.DstPath
	}
	return ""
}

func (this *CopyOutRequest) GetOwner() string {
	if this != nil && this.Owner != nil {
		return *this.Owner
	}
	return ""
}

type CopyOutResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *CopyOutResponse) Reset()         { *this = CopyOutResponse{} }
func (this *CopyOutResponse) String() string { return proto.CompactTextString(this) }
func (*CopyOutResponse) ProtoMessage()       {}

type CreateRequest struct {
	BindMounts       []*CreateRequest_BindMount `protobuf:"bytes,1,rep,name=bind_mounts" json:"bind_mounts,omitempty"`
	GraceTime        *uint32                    `protobuf:"varint,2,opt,name=grace_time" json:"grace_time,omitempty"`
	Handle           *string                    `protobuf:"bytes,3,opt,name=handle" json:"handle,omitempty"`
	Network          *string                    `protobuf:"bytes,4,opt,name=network" json:"network,omitempty"`
	Rootfs           *string                    `protobuf:"bytes,5,opt,name=rootfs" json:"rootfs,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (this *CreateRequest) Reset()         { *this = CreateRequest{} }
func (this *CreateRequest) String() string { return proto.CompactTextString(this) }
func (*CreateRequest) ProtoMessage()       {}

func (this *CreateRequest) GetGraceTime() uint32 {
	if this != nil && this.GraceTime != nil {
		return *this.GraceTime
	}
	return 0
}

func (this *CreateRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *CreateRequest) GetNetwork() string {
	if this != nil && this.Network != nil {
		return *this.Network
	}
	return ""
}

func (this *CreateRequest) GetRootfs() string {
	if this != nil && this.Rootfs != nil {
		return *this.Rootfs
	}
	return ""
}

type CreateRequest_BindMount struct {
	SrcPath          *string                       `protobuf:"bytes,1,req,name=src_path" json:"src_path,omitempty"`
	DstPath          *string                       `protobuf:"bytes,2,req,name=dst_path" json:"dst_path,omitempty"`
	Mode             *CreateRequest_BindMount_Mode `protobuf:"varint,3,req,name=mode,enum=protocol.CreateRequest_BindMount_Mode" json:"mode,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (this *CreateRequest_BindMount) Reset()         { *this = CreateRequest_BindMount{} }
func (this *CreateRequest_BindMount) String() string { return proto.CompactTextString(this) }
func (*CreateRequest_BindMount) ProtoMessage()       {}

func (this *CreateRequest_BindMount) GetSrcPath() string {
	if this != nil && this.SrcPath != nil {
		return *this.SrcPath
	}
	return ""
}

func (this *CreateRequest_BindMount) GetDstPath() string {
	if this != nil && this.DstPath != nil {
		return *this.DstPath
	}
	return ""
}

func (this *CreateRequest_BindMount) GetMode() CreateRequest_BindMount_Mode {
	if this != nil && this.Mode != nil {
		return *this.Mode
	}
	return 0
}

type CreateResponse struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateResponse) Reset()         { *this = CreateResponse{} }
func (this *CreateResponse) String() string { return proto.CompactTextString(this) }
func (*CreateResponse) ProtoMessage()       {}

func (this *CreateResponse) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

type DestroyRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DestroyRequest) Reset()         { *this = DestroyRequest{} }
func (this *DestroyRequest) String() string { return proto.CompactTextString(this) }
func (*DestroyRequest) ProtoMessage()       {}

func (this *DestroyRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

type DestroyResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *DestroyResponse) Reset()         { *this = DestroyResponse{} }
func (this *DestroyResponse) String() string { return proto.CompactTextString(this) }
func (*DestroyResponse) ProtoMessage()       {}

type EchoRequest struct {
	Message          *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *EchoRequest) Reset()         { *this = EchoRequest{} }
func (this *EchoRequest) String() string { return proto.CompactTextString(this) }
func (*EchoRequest) ProtoMessage()       {}

func (this *EchoRequest) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

type EchoResponse struct {
	Message          *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *EchoResponse) Reset()         { *this = EchoResponse{} }
func (this *EchoResponse) String() string { return proto.CompactTextString(this) }
func (*EchoResponse) ProtoMessage()       {}

func (this *EchoResponse) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

type ErrorResponse struct {
	Message          *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data             *string  `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	Backtrace        []string `protobuf:"bytes,3,rep,name=backtrace" json:"backtrace,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *ErrorResponse) Reset()         { *this = ErrorResponse{} }
func (this *ErrorResponse) String() string { return proto.CompactTextString(this) }
func (*ErrorResponse) ProtoMessage()       {}

func (this *ErrorResponse) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

func (this *ErrorResponse) GetData() string {
	if this != nil && this.Data != nil {
		return *this.Data
	}
	return ""
}

type InfoRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *InfoRequest) Reset()         { *this = InfoRequest{} }
func (this *InfoRequest) String() string { return proto.CompactTextString(this) }
func (*InfoRequest) ProtoMessage()       {}

func (this *InfoRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

type InfoResponse struct {
	State            *string                     `protobuf:"bytes,10,opt,name=state" json:"state,omitempty"`
	Events           []string                    `protobuf:"bytes,20,rep,name=events" json:"events,omitempty"`
	HostIp           *string                     `protobuf:"bytes,30,opt,name=host_ip" json:"host_ip,omitempty"`
	ContainerIp      *string                     `protobuf:"bytes,31,opt,name=container_ip" json:"container_ip,omitempty"`
	ContainerPath    *string                     `protobuf:"bytes,32,opt,name=container_path" json:"container_path,omitempty"`
	MemoryStat       *InfoResponse_MemoryStat    `protobuf:"bytes,40,opt,name=memory_stat" json:"memory_stat,omitempty"`
	CpuStat          *InfoResponse_CpuStat       `protobuf:"bytes,41,opt,name=cpu_stat" json:"cpu_stat,omitempty"`
	DiskStat         *InfoResponse_DiskStat      `protobuf:"bytes,42,opt,name=disk_stat" json:"disk_stat,omitempty"`
	BandwidthStat    *InfoResponse_BandwidthStat `protobuf:"bytes,43,opt,name=bandwidth_stat" json:"bandwidth_stat,omitempty"`
	JobIds           []uint64                    `protobuf:"varint,44,rep,name=job_ids" json:"job_ids,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (this *InfoResponse) Reset()         { *this = InfoResponse{} }
func (this *InfoResponse) String() string { return proto.CompactTextString(this) }
func (*InfoResponse) ProtoMessage()       {}

func (this *InfoResponse) GetState() string {
	if this != nil && this.State != nil {
		return *this.State
	}
	return ""
}

func (this *InfoResponse) GetHostIp() string {
	if this != nil && this.HostIp != nil {
		return *this.HostIp
	}
	return ""
}

func (this *InfoResponse) GetContainerIp() string {
	if this != nil && this.ContainerIp != nil {
		return *this.ContainerIp
	}
	return ""
}

func (this *InfoResponse) GetContainerPath() string {
	if this != nil && this.ContainerPath != nil {
		return *this.ContainerPath
	}
	return ""
}

func (this *InfoResponse) GetMemoryStat() *InfoResponse_MemoryStat {
	if this != nil {
		return this.MemoryStat
	}
	return nil
}

func (this *InfoResponse) GetCpuStat() *InfoResponse_CpuStat {
	if this != nil {
		return this.CpuStat
	}
	return nil
}

func (this *InfoResponse) GetDiskStat() *InfoResponse_DiskStat {
	if this != nil {
		return this.DiskStat
	}
	return nil
}

func (this *InfoResponse) GetBandwidthStat() *InfoResponse_BandwidthStat {
	if this != nil {
		return this.BandwidthStat
	}
	return nil
}

type InfoResponse_MemoryStat struct {
	Cache                   *uint64 `protobuf:"varint,1,opt,name=cache" json:"cache,omitempty"`
	Rss                     *uint64 `protobuf:"varint,2,opt,name=rss" json:"rss,omitempty"`
	MappedFile              *uint64 `protobuf:"varint,3,opt,name=mapped_file" json:"mapped_file,omitempty"`
	Pgpgin                  *uint64 `protobuf:"varint,4,opt,name=pgpgin" json:"pgpgin,omitempty"`
	Pgpgout                 *uint64 `protobuf:"varint,5,opt,name=pgpgout" json:"pgpgout,omitempty"`
	Swap                    *uint64 `protobuf:"varint,6,opt,name=swap" json:"swap,omitempty"`
	Pgfault                 *uint64 `protobuf:"varint,7,opt,name=pgfault" json:"pgfault,omitempty"`
	Pgmajfault              *uint64 `protobuf:"varint,8,opt,name=pgmajfault" json:"pgmajfault,omitempty"`
	InactiveAnon            *uint64 `protobuf:"varint,9,opt,name=inactive_anon" json:"inactive_anon,omitempty"`
	ActiveAnon              *uint64 `protobuf:"varint,10,opt,name=active_anon" json:"active_anon,omitempty"`
	InactiveFile            *uint64 `protobuf:"varint,11,opt,name=inactive_file" json:"inactive_file,omitempty"`
	ActiveFile              *uint64 `protobuf:"varint,12,opt,name=active_file" json:"active_file,omitempty"`
	Unevictable             *uint64 `protobuf:"varint,13,opt,name=unevictable" json:"unevictable,omitempty"`
	HierarchicalMemoryLimit *uint64 `protobuf:"varint,14,opt,name=hierarchical_memory_limit" json:"hierarchical_memory_limit,omitempty"`
	HierarchicalMemswLimit  *uint64 `protobuf:"varint,15,opt,name=hierarchical_memsw_limit" json:"hierarchical_memsw_limit,omitempty"`
	TotalCache              *uint64 `protobuf:"varint,16,opt,name=total_cache" json:"total_cache,omitempty"`
	TotalRss                *uint64 `protobuf:"varint,17,opt,name=total_rss" json:"total_rss,omitempty"`
	TotalMappedFile         *uint64 `protobuf:"varint,18,opt,name=total_mapped_file" json:"total_mapped_file,omitempty"`
	TotalPgpgin             *uint64 `protobuf:"varint,19,opt,name=total_pgpgin" json:"total_pgpgin,omitempty"`
	TotalPgpgout            *uint64 `protobuf:"varint,20,opt,name=total_pgpgout" json:"total_pgpgout,omitempty"`
	TotalSwap               *uint64 `protobuf:"varint,21,opt,name=total_swap" json:"total_swap,omitempty"`
	TotalPgfault            *uint64 `protobuf:"varint,22,opt,name=total_pgfault" json:"total_pgfault,omitempty"`
	TotalPgmajfault         *uint64 `protobuf:"varint,23,opt,name=total_pgmajfault" json:"total_pgmajfault,omitempty"`
	TotalInactiveAnon       *uint64 `protobuf:"varint,24,opt,name=total_inactive_anon" json:"total_inactive_anon,omitempty"`
	TotalActiveAnon         *uint64 `protobuf:"varint,25,opt,name=total_active_anon" json:"total_active_anon,omitempty"`
	TotalInactiveFile       *uint64 `protobuf:"varint,26,opt,name=total_inactive_file" json:"total_inactive_file,omitempty"`
	TotalActiveFile         *uint64 `protobuf:"varint,27,opt,name=total_active_file" json:"total_active_file,omitempty"`
	TotalUnevictable        *uint64 `protobuf:"varint,28,opt,name=total_unevictable" json:"total_unevictable,omitempty"`
	XXX_unrecognized        []byte  `json:"-"`
}

func (this *InfoResponse_MemoryStat) Reset()         { *this = InfoResponse_MemoryStat{} }
func (this *InfoResponse_MemoryStat) String() string { return proto.CompactTextString(this) }
func (*InfoResponse_MemoryStat) ProtoMessage()       {}

func (this *InfoResponse_MemoryStat) GetCache() uint64 {
	if this != nil && this.Cache != nil {
		return *this.Cache
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetRss() uint64 {
	if this != nil && this.Rss != nil {
		return *this.Rss
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetMappedFile() uint64 {
	if this != nil && this.MappedFile != nil {
		return *this.MappedFile
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetPgpgin() uint64 {
	if this != nil && this.Pgpgin != nil {
		return *this.Pgpgin
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetPgpgout() uint64 {
	if this != nil && this.Pgpgout != nil {
		return *this.Pgpgout
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetSwap() uint64 {
	if this != nil && this.Swap != nil {
		return *this.Swap
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetPgfault() uint64 {
	if this != nil && this.Pgfault != nil {
		return *this.Pgfault
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetPgmajfault() uint64 {
	if this != nil && this.Pgmajfault != nil {
		return *this.Pgmajfault
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetInactiveAnon() uint64 {
	if this != nil && this.InactiveAnon != nil {
		return *this.InactiveAnon
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetActiveAnon() uint64 {
	if this != nil && this.ActiveAnon != nil {
		return *this.ActiveAnon
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetInactiveFile() uint64 {
	if this != nil && this.InactiveFile != nil {
		return *this.InactiveFile
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetActiveFile() uint64 {
	if this != nil && this.ActiveFile != nil {
		return *this.ActiveFile
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetUnevictable() uint64 {
	if this != nil && this.Unevictable != nil {
		return *this.Unevictable
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetHierarchicalMemoryLimit() uint64 {
	if this != nil && this.HierarchicalMemoryLimit != nil {
		return *this.HierarchicalMemoryLimit
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetHierarchicalMemswLimit() uint64 {
	if this != nil && this.HierarchicalMemswLimit != nil {
		return *this.HierarchicalMemswLimit
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalCache() uint64 {
	if this != nil && this.TotalCache != nil {
		return *this.TotalCache
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalRss() uint64 {
	if this != nil && this.TotalRss != nil {
		return *this.TotalRss
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalMappedFile() uint64 {
	if this != nil && this.TotalMappedFile != nil {
		return *this.TotalMappedFile
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalPgpgin() uint64 {
	if this != nil && this.TotalPgpgin != nil {
		return *this.TotalPgpgin
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalPgpgout() uint64 {
	if this != nil && this.TotalPgpgout != nil {
		return *this.TotalPgpgout
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalSwap() uint64 {
	if this != nil && this.TotalSwap != nil {
		return *this.TotalSwap
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalPgfault() uint64 {
	if this != nil && this.TotalPgfault != nil {
		return *this.TotalPgfault
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalPgmajfault() uint64 {
	if this != nil && this.TotalPgmajfault != nil {
		return *this.TotalPgmajfault
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalInactiveAnon() uint64 {
	if this != nil && this.TotalInactiveAnon != nil {
		return *this.TotalInactiveAnon
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalActiveAnon() uint64 {
	if this != nil && this.TotalActiveAnon != nil {
		return *this.TotalActiveAnon
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalInactiveFile() uint64 {
	if this != nil && this.TotalInactiveFile != nil {
		return *this.TotalInactiveFile
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalActiveFile() uint64 {
	if this != nil && this.TotalActiveFile != nil {
		return *this.TotalActiveFile
	}
	return 0
}

func (this *InfoResponse_MemoryStat) GetTotalUnevictable() uint64 {
	if this != nil && this.TotalUnevictable != nil {
		return *this.TotalUnevictable
	}
	return 0
}

type InfoResponse_CpuStat struct {
	Usage            *uint64 `protobuf:"varint,1,opt,name=usage" json:"usage,omitempty"`
	User             *uint64 `protobuf:"varint,2,opt,name=user" json:"user,omitempty"`
	System           *uint64 `protobuf:"varint,3,opt,name=system" json:"system,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *InfoResponse_CpuStat) Reset()         { *this = InfoResponse_CpuStat{} }
func (this *InfoResponse_CpuStat) String() string { return proto.CompactTextString(this) }
func (*InfoResponse_CpuStat) ProtoMessage()       {}

func (this *InfoResponse_CpuStat) GetUsage() uint64 {
	if this != nil && this.Usage != nil {
		return *this.Usage
	}
	return 0
}

func (this *InfoResponse_CpuStat) GetUser() uint64 {
	if this != nil && this.User != nil {
		return *this.User
	}
	return 0
}

func (this *InfoResponse_CpuStat) GetSystem() uint64 {
	if this != nil && this.System != nil {
		return *this.System
	}
	return 0
}

type InfoResponse_DiskStat struct {
	BytesUsed        *uint64 `protobuf:"varint,1,opt,name=bytes_used" json:"bytes_used,omitempty"`
	InodesUsed       *uint64 `protobuf:"varint,2,opt,name=inodes_used" json:"inodes_used,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *InfoResponse_DiskStat) Reset()         { *this = InfoResponse_DiskStat{} }
func (this *InfoResponse_DiskStat) String() string { return proto.CompactTextString(this) }
func (*InfoResponse_DiskStat) ProtoMessage()       {}

func (this *InfoResponse_DiskStat) GetBytesUsed() uint64 {
	if this != nil && this.BytesUsed != nil {
		return *this.BytesUsed
	}
	return 0
}

func (this *InfoResponse_DiskStat) GetInodesUsed() uint64 {
	if this != nil && this.InodesUsed != nil {
		return *this.InodesUsed
	}
	return 0
}

type InfoResponse_BandwidthStat struct {
	InRate           *uint64 `protobuf:"varint,1,opt,name=in_rate" json:"in_rate,omitempty"`
	InBurst          *uint64 `protobuf:"varint,2,opt,name=in_burst" json:"in_burst,omitempty"`
	OutRate          *uint64 `protobuf:"varint,3,opt,name=out_rate" json:"out_rate,omitempty"`
	OutBurst         *uint64 `protobuf:"varint,4,opt,name=out_burst" json:"out_burst,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *InfoResponse_BandwidthStat) Reset()         { *this = InfoResponse_BandwidthStat{} }
func (this *InfoResponse_BandwidthStat) String() string { return proto.CompactTextString(this) }
func (*InfoResponse_BandwidthStat) ProtoMessage()       {}

func (this *InfoResponse_BandwidthStat) GetInRate() uint64 {
	if this != nil && this.InRate != nil {
		return *this.InRate
	}
	return 0
}

func (this *InfoResponse_BandwidthStat) GetInBurst() uint64 {
	if this != nil && this.InBurst != nil {
		return *this.InBurst
	}
	return 0
}

func (this *InfoResponse_BandwidthStat) GetOutRate() uint64 {
	if this != nil && this.OutRate != nil {
		return *this.OutRate
	}
	return 0
}

func (this *InfoResponse_BandwidthStat) GetOutBurst() uint64 {
	if this != nil && this.OutBurst != nil {
		return *this.OutBurst
	}
	return 0
}

type LimitBandwidthRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Rate             *uint64 `protobuf:"varint,2,opt,name=rate" json:"rate,omitempty"`
	Burst            *uint64 `protobuf:"varint,3,opt,name=burst" json:"burst,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LimitBandwidthRequest) Reset()         { *this = LimitBandwidthRequest{} }
func (this *LimitBandwidthRequest) String() string { return proto.CompactTextString(this) }
func (*LimitBandwidthRequest) ProtoMessage()       {}

func (this *LimitBandwidthRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *LimitBandwidthRequest) GetRate() uint64 {
	if this != nil && this.Rate != nil {
		return *this.Rate
	}
	return 0
}

func (this *LimitBandwidthRequest) GetBurst() uint64 {
	if this != nil && this.Burst != nil {
		return *this.Burst
	}
	return 0
}

type LimitBandwidthResponse struct {
	Rate             *uint64 `protobuf:"varint,1,opt,name=rate" json:"rate,omitempty"`
	Burst            *uint64 `protobuf:"varint,2,opt,name=burst" json:"burst,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LimitBandwidthResponse) Reset()         { *this = LimitBandwidthResponse{} }
func (this *LimitBandwidthResponse) String() string { return proto.CompactTextString(this) }
func (*LimitBandwidthResponse) ProtoMessage()       {}

func (this *LimitBandwidthResponse) GetRate() uint64 {
	if this != nil && this.Rate != nil {
		return *this.Rate
	}
	return 0
}

func (this *LimitBandwidthResponse) GetBurst() uint64 {
	if this != nil && this.Burst != nil {
		return *this.Burst
	}
	return 0
}

type LimitDiskRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	BlockLimit       *uint32 `protobuf:"varint,10,opt,name=block_limit" json:"block_limit,omitempty"`
	Block            *uint64 `protobuf:"varint,11,opt,name=block" json:"block,omitempty"`
	BlockSoft        *uint64 `protobuf:"varint,12,opt,name=block_soft" json:"block_soft,omitempty"`
	BlockHard        *uint64 `protobuf:"varint,13,opt,name=block_hard" json:"block_hard,omitempty"`
	InodeLimit       *uint32 `protobuf:"varint,20,opt,name=inode_limit" json:"inode_limit,omitempty"`
	Inode            *uint64 `protobuf:"varint,21,opt,name=inode" json:"inode,omitempty"`
	InodeSoft        *uint64 `protobuf:"varint,22,opt,name=inode_soft" json:"inode_soft,omitempty"`
	InodeHard        *uint64 `protobuf:"varint,23,opt,name=inode_hard" json:"inode_hard,omitempty"`
	ByteLimit        *uint32 `protobuf:"varint,30,opt,name=byte_limit" json:"byte_limit,omitempty"`
	Byte             *uint64 `protobuf:"varint,31,opt,name=byte" json:"byte,omitempty"`
	ByteSoft         *uint64 `protobuf:"varint,32,opt,name=byte_soft" json:"byte_soft,omitempty"`
	ByteHard         *uint64 `protobuf:"varint,33,opt,name=byte_hard" json:"byte_hard,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LimitDiskRequest) Reset()         { *this = LimitDiskRequest{} }
func (this *LimitDiskRequest) String() string { return proto.CompactTextString(this) }
func (*LimitDiskRequest) ProtoMessage()       {}

func (this *LimitDiskRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *LimitDiskRequest) GetBlockLimit() uint32 {
	if this != nil && this.BlockLimit != nil {
		return *this.BlockLimit
	}
	return 0
}

func (this *LimitDiskRequest) GetBlock() uint64 {
	if this != nil && this.Block != nil {
		return *this.Block
	}
	return 0
}

func (this *LimitDiskRequest) GetBlockSoft() uint64 {
	if this != nil && this.BlockSoft != nil {
		return *this.BlockSoft
	}
	return 0
}

func (this *LimitDiskRequest) GetBlockHard() uint64 {
	if this != nil && this.BlockHard != nil {
		return *this.BlockHard
	}
	return 0
}

func (this *LimitDiskRequest) GetInodeLimit() uint32 {
	if this != nil && this.InodeLimit != nil {
		return *this.InodeLimit
	}
	return 0
}

func (this *LimitDiskRequest) GetInode() uint64 {
	if this != nil && this.Inode != nil {
		return *this.Inode
	}
	return 0
}

func (this *LimitDiskRequest) GetInodeSoft() uint64 {
	if this != nil && this.InodeSoft != nil {
		return *this.InodeSoft
	}
	return 0
}

func (this *LimitDiskRequest) GetInodeHard() uint64 {
	if this != nil && this.InodeHard != nil {
		return *this.InodeHard
	}
	return 0
}

func (this *LimitDiskRequest) GetByteLimit() uint32 {
	if this != nil && this.ByteLimit != nil {
		return *this.ByteLimit
	}
	return 0
}

func (this *LimitDiskRequest) GetByte() uint64 {
	if this != nil && this.Byte != nil {
		return *this.Byte
	}
	return 0
}

func (this *LimitDiskRequest) GetByteSoft() uint64 {
	if this != nil && this.ByteSoft != nil {
		return *this.ByteSoft
	}
	return 0
}

func (this *LimitDiskRequest) GetByteHard() uint64 {
	if this != nil && this.ByteHard != nil {
		return *this.ByteHard
	}
	return 0
}

type LimitDiskResponse struct {
	BlockLimit       *uint32 `protobuf:"varint,10,opt,name=block_limit" json:"block_limit,omitempty"`
	Block            *uint64 `protobuf:"varint,11,opt,name=block" json:"block,omitempty"`
	BlockSoft        *uint64 `protobuf:"varint,12,opt,name=block_soft" json:"block_soft,omitempty"`
	BlockHard        *uint64 `protobuf:"varint,13,opt,name=block_hard" json:"block_hard,omitempty"`
	InodeLimit       *uint32 `protobuf:"varint,20,opt,name=inode_limit" json:"inode_limit,omitempty"`
	Inode            *uint64 `protobuf:"varint,21,opt,name=inode" json:"inode,omitempty"`
	InodeSoft        *uint64 `protobuf:"varint,22,opt,name=inode_soft" json:"inode_soft,omitempty"`
	InodeHard        *uint64 `protobuf:"varint,23,opt,name=inode_hard" json:"inode_hard,omitempty"`
	ByteLimit        *uint32 `protobuf:"varint,30,opt,name=byte_limit" json:"byte_limit,omitempty"`
	Byte             *uint64 `protobuf:"varint,31,opt,name=byte" json:"byte,omitempty"`
	ByteSoft         *uint64 `protobuf:"varint,32,opt,name=byte_soft" json:"byte_soft,omitempty"`
	ByteHard         *uint64 `protobuf:"varint,33,opt,name=byte_hard" json:"byte_hard,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LimitDiskResponse) Reset()         { *this = LimitDiskResponse{} }
func (this *LimitDiskResponse) String() string { return proto.CompactTextString(this) }
func (*LimitDiskResponse) ProtoMessage()       {}

func (this *LimitDiskResponse) GetBlockLimit() uint32 {
	if this != nil && this.BlockLimit != nil {
		return *this.BlockLimit
	}
	return 0
}

func (this *LimitDiskResponse) GetBlock() uint64 {
	if this != nil && this.Block != nil {
		return *this.Block
	}
	return 0
}

func (this *LimitDiskResponse) GetBlockSoft() uint64 {
	if this != nil && this.BlockSoft != nil {
		return *this.BlockSoft
	}
	return 0
}

func (this *LimitDiskResponse) GetBlockHard() uint64 {
	if this != nil && this.BlockHard != nil {
		return *this.BlockHard
	}
	return 0
}

func (this *LimitDiskResponse) GetInodeLimit() uint32 {
	if this != nil && this.InodeLimit != nil {
		return *this.InodeLimit
	}
	return 0
}

func (this *LimitDiskResponse) GetInode() uint64 {
	if this != nil && this.Inode != nil {
		return *this.Inode
	}
	return 0
}

func (this *LimitDiskResponse) GetInodeSoft() uint64 {
	if this != nil && this.InodeSoft != nil {
		return *this.InodeSoft
	}
	return 0
}

func (this *LimitDiskResponse) GetInodeHard() uint64 {
	if this != nil && this.InodeHard != nil {
		return *this.InodeHard
	}
	return 0
}

func (this *LimitDiskResponse) GetByteLimit() uint32 {
	if this != nil && this.ByteLimit != nil {
		return *this.ByteLimit
	}
	return 0
}

func (this *LimitDiskResponse) GetByte() uint64 {
	if this != nil && this.Byte != nil {
		return *this.Byte
	}
	return 0
}

func (this *LimitDiskResponse) GetByteSoft() uint64 {
	if this != nil && this.ByteSoft != nil {
		return *this.ByteSoft
	}
	return 0
}

func (this *LimitDiskResponse) GetByteHard() uint64 {
	if this != nil && this.ByteHard != nil {
		return *this.ByteHard
	}
	return 0
}

type LimitMemoryRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	LimitInBytes     *uint64 `protobuf:"varint,2,opt,name=limit_in_bytes" json:"limit_in_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LimitMemoryRequest) Reset()         { *this = LimitMemoryRequest{} }
func (this *LimitMemoryRequest) String() string { return proto.CompactTextString(this) }
func (*LimitMemoryRequest) ProtoMessage()       {}

func (this *LimitMemoryRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *LimitMemoryRequest) GetLimitInBytes() uint64 {
	if this != nil && this.LimitInBytes != nil {
		return *this.LimitInBytes
	}
	return 0
}

type LimitMemoryResponse struct {
	LimitInBytes     *uint64 `protobuf:"varint,1,opt,name=limit_in_bytes" json:"limit_in_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LimitMemoryResponse) Reset()         { *this = LimitMemoryResponse{} }
func (this *LimitMemoryResponse) String() string { return proto.CompactTextString(this) }
func (*LimitMemoryResponse) ProtoMessage()       {}

func (this *LimitMemoryResponse) GetLimitInBytes() uint64 {
	if this != nil && this.LimitInBytes != nil {
		return *this.LimitInBytes
	}
	return 0
}

type LinkRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	JobId            *uint32 `protobuf:"varint,2,req,name=job_id" json:"job_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LinkRequest) Reset()         { *this = LinkRequest{} }
func (this *LinkRequest) String() string { return proto.CompactTextString(this) }
func (*LinkRequest) ProtoMessage()       {}

func (this *LinkRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *LinkRequest) GetJobId() uint32 {
	if this != nil && this.JobId != nil {
		return *this.JobId
	}
	return 0
}

type LinkResponse struct {
	ExitStatus       *uint32 `protobuf:"varint,1,opt,name=exit_status" json:"exit_status,omitempty"`
	Stdout           *string `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr           *string `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LinkResponse) Reset()         { *this = LinkResponse{} }
func (this *LinkResponse) String() string { return proto.CompactTextString(this) }
func (*LinkResponse) ProtoMessage()       {}

func (this *LinkResponse) GetExitStatus() uint32 {
	if this != nil && this.ExitStatus != nil {
		return *this.ExitStatus
	}
	return 0
}

func (this *LinkResponse) GetStdout() string {
	if this != nil && this.Stdout != nil {
		return *this.Stdout
	}
	return ""
}

func (this *LinkResponse) GetStderr() string {
	if this != nil && this.Stderr != nil {
		return *this.Stderr
	}
	return ""
}

type ListRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *ListRequest) Reset()         { *this = ListRequest{} }
func (this *ListRequest) String() string { return proto.CompactTextString(this) }
func (*ListRequest) ProtoMessage()       {}

type ListResponse struct {
	Handles          []string `protobuf:"bytes,1,rep,name=handles" json:"handles,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *ListResponse) Reset()         { *this = ListResponse{} }
func (this *ListResponse) String() string { return proto.CompactTextString(this) }
func (*ListResponse) ProtoMessage()       {}

type Message struct {
	Type             *Message_Type `protobuf:"varint,1,req,name=type,enum=protocol.Message_Type" json:"type,omitempty"`
	Payload          []byte        `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *Message) Reset()         { *this = Message{} }
func (this *Message) String() string { return proto.CompactTextString(this) }
func (*Message) ProtoMessage()       {}

func (this *Message) GetType() Message_Type {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Message) GetPayload() []byte {
	if this != nil {
		return this.Payload
	}
	return nil
}

type NetInRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	HostPort         *uint32 `protobuf:"varint,3,opt,name=host_port" json:"host_port,omitempty"`
	ContainerPort    *uint32 `protobuf:"varint,2,opt,name=container_port" json:"container_port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *NetInRequest) Reset()         { *this = NetInRequest{} }
func (this *NetInRequest) String() string { return proto.CompactTextString(this) }
func (*NetInRequest) ProtoMessage()       {}

func (this *NetInRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *NetInRequest) GetHostPort() uint32 {
	if this != nil && this.HostPort != nil {
		return *this.HostPort
	}
	return 0
}

func (this *NetInRequest) GetContainerPort() uint32 {
	if this != nil && this.ContainerPort != nil {
		return *this.ContainerPort
	}
	return 0
}

type NetInResponse struct {
	HostPort         *uint32 `protobuf:"varint,1,opt,name=host_port" json:"host_port,omitempty"`
	ContainerPort    *uint32 `protobuf:"varint,2,opt,name=container_port" json:"container_port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *NetInResponse) Reset()         { *this = NetInResponse{} }
func (this *NetInResponse) String() string { return proto.CompactTextString(this) }
func (*NetInResponse) ProtoMessage()       {}

func (this *NetInResponse) GetHostPort() uint32 {
	if this != nil && this.HostPort != nil {
		return *this.HostPort
	}
	return 0
}

func (this *NetInResponse) GetContainerPort() uint32 {
	if this != nil && this.ContainerPort != nil {
		return *this.ContainerPort
	}
	return 0
}

type NetOutRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Network          *string `protobuf:"bytes,2,opt,name=network" json:"network,omitempty"`
	Port             *uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *NetOutRequest) Reset()         { *this = NetOutRequest{} }
func (this *NetOutRequest) String() string { return proto.CompactTextString(this) }
func (*NetOutRequest) ProtoMessage()       {}

func (this *NetOutRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *NetOutRequest) GetNetwork() string {
	if this != nil && this.Network != nil {
		return *this.Network
	}
	return ""
}

func (this *NetOutRequest) GetPort() uint32 {
	if this != nil && this.Port != nil {
		return *this.Port
	}
	return 0
}

type NetOutResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *NetOutResponse) Reset()         { *this = NetOutResponse{} }
func (this *NetOutResponse) String() string { return proto.CompactTextString(this) }
func (*NetOutResponse) ProtoMessage()       {}

type PingRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *PingRequest) Reset()         { *this = PingRequest{} }
func (this *PingRequest) String() string { return proto.CompactTextString(this) }
func (*PingRequest) ProtoMessage()       {}

type PingResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *PingResponse) Reset()         { *this = PingResponse{} }
func (this *PingResponse) String() string { return proto.CompactTextString(this) }
func (*PingResponse) ProtoMessage()       {}

type ResourceLimits struct {
	As               *uint64 `protobuf:"varint,1,opt,name=as" json:"as,omitempty"`
	Core             *uint64 `protobuf:"varint,2,opt,name=core" json:"core,omitempty"`
	Cpu              *uint64 `protobuf:"varint,3,opt,name=cpu" json:"cpu,omitempty"`
	Data             *uint64 `protobuf:"varint,4,opt,name=data" json:"data,omitempty"`
	Fsize            *uint64 `protobuf:"varint,5,opt,name=fsize" json:"fsize,omitempty"`
	Locks            *uint64 `protobuf:"varint,6,opt,name=locks" json:"locks,omitempty"`
	Memlock          *uint64 `protobuf:"varint,7,opt,name=memlock" json:"memlock,omitempty"`
	Msgqueue         *uint64 `protobuf:"varint,8,opt,name=msgqueue" json:"msgqueue,omitempty"`
	Nice             *uint64 `protobuf:"varint,9,opt,name=nice" json:"nice,omitempty"`
	Nofile           *uint64 `protobuf:"varint,10,opt,name=nofile" json:"nofile,omitempty"`
	Nproc            *uint64 `protobuf:"varint,11,opt,name=nproc" json:"nproc,omitempty"`
	Rss              *uint64 `protobuf:"varint,12,opt,name=rss" json:"rss,omitempty"`
	Rtprio           *uint64 `protobuf:"varint,13,opt,name=rtprio" json:"rtprio,omitempty"`
	Sigpending       *uint64 `protobuf:"varint,14,opt,name=sigpending" json:"sigpending,omitempty"`
	Stack            *uint64 `protobuf:"varint,15,opt,name=stack" json:"stack,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ResourceLimits) Reset()         { *this = ResourceLimits{} }
func (this *ResourceLimits) String() string { return proto.CompactTextString(this) }
func (*ResourceLimits) ProtoMessage()       {}

func (this *ResourceLimits) GetAs() uint64 {
	if this != nil && this.As != nil {
		return *this.As
	}
	return 0
}

func (this *ResourceLimits) GetCore() uint64 {
	if this != nil && this.Core != nil {
		return *this.Core
	}
	return 0
}

func (this *ResourceLimits) GetCpu() uint64 {
	if this != nil && this.Cpu != nil {
		return *this.Cpu
	}
	return 0
}

func (this *ResourceLimits) GetData() uint64 {
	if this != nil && this.Data != nil {
		return *this.Data
	}
	return 0
}

func (this *ResourceLimits) GetFsize() uint64 {
	if this != nil && this.Fsize != nil {
		return *this.Fsize
	}
	return 0
}

func (this *ResourceLimits) GetLocks() uint64 {
	if this != nil && this.Locks != nil {
		return *this.Locks
	}
	return 0
}

func (this *ResourceLimits) GetMemlock() uint64 {
	if this != nil && this.Memlock != nil {
		return *this.Memlock
	}
	return 0
}

func (this *ResourceLimits) GetMsgqueue() uint64 {
	if this != nil && this.Msgqueue != nil {
		return *this.Msgqueue
	}
	return 0
}

func (this *ResourceLimits) GetNice() uint64 {
	if this != nil && this.Nice != nil {
		return *this.Nice
	}
	return 0
}

func (this *ResourceLimits) GetNofile() uint64 {
	if this != nil && this.Nofile != nil {
		return *this.Nofile
	}
	return 0
}

func (this *ResourceLimits) GetNproc() uint64 {
	if this != nil && this.Nproc != nil {
		return *this.Nproc
	}
	return 0
}

func (this *ResourceLimits) GetRss() uint64 {
	if this != nil && this.Rss != nil {
		return *this.Rss
	}
	return 0
}

func (this *ResourceLimits) GetRtprio() uint64 {
	if this != nil && this.Rtprio != nil {
		return *this.Rtprio
	}
	return 0
}

func (this *ResourceLimits) GetSigpending() uint64 {
	if this != nil && this.Sigpending != nil {
		return *this.Sigpending
	}
	return 0
}

func (this *ResourceLimits) GetStack() uint64 {
	if this != nil && this.Stack != nil {
		return *this.Stack
	}
	return 0
}

type RunRequest struct {
	Handle           *string         `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Script           *string         `protobuf:"bytes,2,req,name=script" json:"script,omitempty"`
	Privileged       *bool           `protobuf:"varint,3,opt,name=privileged,def=0" json:"privileged,omitempty"`
	Rlimits          *ResourceLimits `protobuf:"bytes,4,opt,name=rlimits" json:"rlimits,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *RunRequest) Reset()         { *this = RunRequest{} }
func (this *RunRequest) String() string { return proto.CompactTextString(this) }
func (*RunRequest) ProtoMessage()       {}

const Default_RunRequest_Privileged bool = false

func (this *RunRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *RunRequest) GetScript() string {
	if this != nil && this.Script != nil {
		return *this.Script
	}
	return ""
}

func (this *RunRequest) GetPrivileged() bool {
	if this != nil && this.Privileged != nil {
		return *this.Privileged
	}
	return Default_RunRequest_Privileged
}

func (this *RunRequest) GetRlimits() *ResourceLimits {
	if this != nil {
		return this.Rlimits
	}
	return nil
}

type RunResponse struct {
	ExitStatus       *uint32 `protobuf:"varint,1,opt,name=exit_status" json:"exit_status,omitempty"`
	Stdout           *string `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr           *string `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RunResponse) Reset()         { *this = RunResponse{} }
func (this *RunResponse) String() string { return proto.CompactTextString(this) }
func (*RunResponse) ProtoMessage()       {}

func (this *RunResponse) GetExitStatus() uint32 {
	if this != nil && this.ExitStatus != nil {
		return *this.ExitStatus
	}
	return 0
}

func (this *RunResponse) GetStdout() string {
	if this != nil && this.Stdout != nil {
		return *this.Stdout
	}
	return ""
}

func (this *RunResponse) GetStderr() string {
	if this != nil && this.Stderr != nil {
		return *this.Stderr
	}
	return ""
}

type SpawnRequest struct {
	Handle           *string         `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Script           *string         `protobuf:"bytes,2,req,name=script" json:"script,omitempty"`
	Privileged       *bool           `protobuf:"varint,3,opt,name=privileged,def=0" json:"privileged,omitempty"`
	Rlimits          *ResourceLimits `protobuf:"bytes,4,opt,name=rlimits" json:"rlimits,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *SpawnRequest) Reset()         { *this = SpawnRequest{} }
func (this *SpawnRequest) String() string { return proto.CompactTextString(this) }
func (*SpawnRequest) ProtoMessage()       {}

const Default_SpawnRequest_Privileged bool = false

func (this *SpawnRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *SpawnRequest) GetScript() string {
	if this != nil && this.Script != nil {
		return *this.Script
	}
	return ""
}

func (this *SpawnRequest) GetPrivileged() bool {
	if this != nil && this.Privileged != nil {
		return *this.Privileged
	}
	return Default_SpawnRequest_Privileged
}

func (this *SpawnRequest) GetRlimits() *ResourceLimits {
	if this != nil {
		return this.Rlimits
	}
	return nil
}

type SpawnResponse struct {
	JobId            *uint32 `protobuf:"varint,1,req,name=job_id" json:"job_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *SpawnResponse) Reset()         { *this = SpawnResponse{} }
func (this *SpawnResponse) String() string { return proto.CompactTextString(this) }
func (*SpawnResponse) ProtoMessage()       {}

func (this *SpawnResponse) GetJobId() uint32 {
	if this != nil && this.JobId != nil {
		return *this.JobId
	}
	return 0
}

type StopRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Background       *bool   `protobuf:"varint,10,opt,name=background,def=0" json:"background,omitempty"`
	Kill             *bool   `protobuf:"varint,20,opt,name=kill,def=0" json:"kill,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StopRequest) Reset()         { *this = StopRequest{} }
func (this *StopRequest) String() string { return proto.CompactTextString(this) }
func (*StopRequest) ProtoMessage()       {}

const Default_StopRequest_Background bool = false
const Default_StopRequest_Kill bool = false

func (this *StopRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *StopRequest) GetBackground() bool {
	if this != nil && this.Background != nil {
		return *this.Background
	}
	return Default_StopRequest_Background
}

func (this *StopRequest) GetKill() bool {
	if this != nil && this.Kill != nil {
		return *this.Kill
	}
	return Default_StopRequest_Kill
}

type StopResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *StopResponse) Reset()         { *this = StopResponse{} }
func (this *StopResponse) String() string { return proto.CompactTextString(this) }
func (*StopResponse) ProtoMessage()       {}

type StreamRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	JobId            *uint32 `protobuf:"varint,2,req,name=job_id" json:"job_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StreamRequest) Reset()         { *this = StreamRequest{} }
func (this *StreamRequest) String() string { return proto.CompactTextString(this) }
func (*StreamRequest) ProtoMessage()       {}

func (this *StreamRequest) GetHandle() string {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return ""
}

func (this *StreamRequest) GetJobId() uint32 {
	if this != nil && this.JobId != nil {
		return *this.JobId
	}
	return 0
}

type StreamResponse struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Data             *string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	ExitStatus       *uint32 `protobuf:"varint,3,opt,name=exit_status" json:"exit_status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StreamResponse) Reset()         { *this = StreamResponse{} }
func (this *StreamResponse) String() string { return proto.CompactTextString(this) }
func (*StreamResponse) ProtoMessage()       {}

func (this *StreamResponse) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *StreamResponse) GetData() string {
	if this != nil && this.Data != nil {
		return *this.Data
	}
	return ""
}

func (this *StreamResponse) GetExitStatus() uint32 {
	if this != nil && this.ExitStatus != nil {
		return *this.ExitStatus
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.CreateRequest_BindMount_Mode", CreateRequest_BindMount_Mode_name, CreateRequest_BindMount_Mode_value)
	proto.RegisterEnum("protocol.Message_Type", Message_Type_name, Message_Type_value)
}
